# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x1d\n\x0b\x43hatRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\"@\n\x0c\x43hatResponse\x12\x0e\n\x06\x43hatID\x18\x01 \x01(\t\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07IsError\x18\x03 \x01(\x08\"B\n\rCreateRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x64oc_text\x18\x03 \x01(\t\"B\n\x0e\x43reateResponse\x12\x0e\n\x06\x43hatID\x18\x01 \x01(\t\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0f\n\x07IsError\x18\x03 \x01(\x08\x32\x81\x01\n\x07Service\x12\x37\n\x08GetChats\x12\x14.service.ChatRequest\x1a\x15.service.ChatResponse\x12=\n\nCreateChat\x12\x16.service.CreateRequest\x1a\x17.service.CreateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=26
  _globals['_CHATREQUEST']._serialized_end=55
  _globals['_CHATRESPONSE']._serialized_start=57
  _globals['_CHATRESPONSE']._serialized_end=121
  _globals['_CREATEREQUEST']._serialized_start=123
  _globals['_CREATEREQUEST']._serialized_end=189
  _globals['_CREATERESPONSE']._serialized_start=191
  _globals['_CREATERESPONSE']._serialized_end=257
  _globals['_SERVICE']._serialized_start=260
  _globals['_SERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
