// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForCreateQAHistoryBatch implements pgx.CopyFromSource.
type iteratorForCreateQAHistoryBatch struct {
	rows                 []CreateQAHistoryBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateQAHistoryBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateQAHistoryBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChatID,
		r.rows[0].Question,
		r.rows[0].Answer,
		r.rows[0].Timestamp,
	}, nil
}

func (r iteratorForCreateQAHistoryBatch) Err() error {
	return nil
}

func (q *Queries) CreateQAHistoryBatch(ctx context.Context, arg []CreateQAHistoryBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"qa_histories"}, []string{"id", "chat_id", "question", "answer", "timestamp"}, &iteratorForCreateQAHistoryBatch{rows: arg})
}
