// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateQAHistory(ctx context.Context, arg CreateQAHistoryParams) (QaHistory, error)
	CreateQAHistoryBatch(ctx context.Context, arg []CreateQAHistoryBatchParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChatByDocID(ctx context.Context, docID string) (Chat, error)
	GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error)
	GetQAHistoriesByChatID(ctx context.Context, chatID uuid.UUID) ([]QaHistory, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserChats(ctx context.Context, userID uuid.UUID) ([]GetUserChatsRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
