.PHONY: migrate rollback migrate-status run

migrate:
    go run cmd/main.go up

rollback:
    go run cmd/main.go down

migrate-status:
    go run cmd/main.go status

run:
    go run main.go

dev:
    air